=== nlct/flowframtk/src/doc/flowframtk.dtd
<!-- Parameter entities -->
<!ENTITY % basic.content '#PCDATA | dict | tt | em | br | url | sty | cli | acr | image | opt | ref | term | plural | tabular | menu | dq | TeX LaTeX | nbsp | qquad | fndagmark | meta | dl | app | appversion | applink | verbinput | cs | env | envvar | hash | emdash | ldots | cont | button' >

<!-- Main elements-->

<!ELEMENT manual (preamble, document)>
<!ATTLIST manual fontenc (#PCDATA)+>
<!ELEMENT preamble (title, author+, date, newacro*, newterm*)>
<!ELEMENT document (node+ | printglossary | printindex)>

<!-- Preamble elements-->

<!ELEMENT date (%basic.content;)+>
<!ELEMENT newacro EMPTY>
<!ATTLIST newacro tag (#PCDATA)+ #REQUIRED>
<!ATTLIST newacro short (%basic.content;)+ #REQUIRED>
<!ATTLIST newacro long (%basic.content;)+ #REQUIRED>
<!ATTLIST newacro description (%basic.content;)+>
<!ELEMENT newterm EMPTY>
<!ATTLIST newterm tag (#PCDATA)+ #REQUIRED>
<!ATTLIST newterm text (%basic.content;)+ #REQUIRED>
<!ATTLIST newterm description (%basic.content;)+>
<!ELEMENT author (%basic.content;)+>
<!ELEMENT translator (%basic.content;)+>

<!-- Document elements -->

<!ELEMENT boilerplate (p | pre | alltt | prompt | verbtabinput | htmlonly | latexonly )+ >
<!ELEMENT printindex EMPTY>
<!ELEMENT printglossary EMPTY>
<!ELEMENT tableofcontents EMPTY>
<!ELEMENT frontmatter EMPTY>
<!ELEMENT mainmatter EMPTY>
<!ELEMENT backmatter EMPTY>

<!ELEMENT node (p | float | pre | alltt | prompt | dl | ul | ol | verbtabinput | htmlonly | latexonly )+ | printglossary | printindex >
<!ATTLIST node tag (#PCDATA)+ #REQUIRED>
<!ATTLIST node type (#PCDATA)+ #REQUIRED>
<!ATTLIST node title (%basic.content;)+ #REQUIRED>
<!ATTLIST node pos (#PCDATA)+ #REQUIRED>

<!-- Basic elements -->
<!ELEMENT p (%basic.content;)*>
<!ATTLIST p align (#PCDATA)+>
<!ATTLIST p noindent (#PCDATA)+>
<!ATTLIST p class (#PCDATA)+>
<!ELEMENT url EMPTY>
<!ATTLIST url www (#PCDATA)+ #REQUIRED>
<!ATTLIST url text (#PCDATA)+>
<!ELEMENT dict EMPTY>
<!ATTLIST dict tag (#PCDATA)+ #REQUIRED>
<!ATTLIST dict arg1 (%basic.content;)+>
<!ATTLIST dict arg2 (%basic.content;)+>
<!ATTLIST dict arg3 (%basic.content;)+>
<!ATTLIST dict arg4 (%basic.content;)+>
<!ATTLIST dict arg5 (%basic.content;)+>
<!ATTLIST dict arg6 (%basic.content;)+>
<!ATTLIST dict arg7 (%basic.content;)+>
<!ATTLIST dict arg8 (%basic.content;)+>
<!ATTLIST dict arg9 (%basic.content;)+>
<!ELEMENT button EMPTY>
<!ATTLIST button tag (#PCDATA)+ #REQUIRED>
<!ELEMENT ref (%basic.content;)+>
<!ATTLIST ref tag (#PCDATA)+ #REQUIRED>
<!ELEMENT menu EMPTY>
<!ATTLIST menu tag (#PCDATA)+ #REQUIRED>
<!ELEMENT opt EMPTY >
<!ATTLIST opt tag (#PCDATA)+ #REQUIRED>
<!ELEMENT applink (%basic.content;)+>
<!ELEMENT dq (%basic.content;)+>
<!ELEMENT tt (%basic.content;)+>
<!ELEMENT meta (%basic.content;)+>
<!ELEMENT sty EMPTY >
<!ATTLIST sty tag (%basic.content;)+>
<!ELEMENT em (%basic.content;)+>
<!ELEMENT b (%basic.content;)+>
<!ELEMENT pre (%basic.content;)+>
<!ELEMENT alltt (%basic.content;)+>
<!ELEMENT prompt (%basic.content;)+>
<!ELEMENT float (%basic.content;)+>
<!ATTLIST float type (#PCDATA)+ #REQUIRED>
<!ATTLIST float tag (#PCDATA)+ #REQUIRED>
<!ATTLIST float listcaption (%basic.content;)+>
<!ATTLIST float spec (%basic.content;)+>
<!ELEMENT caption (%basic.content;)+>
<!ELEMENT tableheading (tr)+>
<!ELEMENT tablefooter (tr)+>
<!ELEMENT dl (dt, dd)+>
<!ELEMENT dt (%basic.content;)+>
<!ELEMENT dd (%basic.content;)+>
<!ELEMENT htmlonly (%basic.content;)+>
<!ELEMENT latexonly (%basic.content;)+>
<!ELEMENT kbd EMPTY>
<!ATTLIST kbd key (#PCDATA)+ #REQUIRED>

<!ELEMENT image EMPTY>
<!ATTLIST image src (%basic.content;)+>
<!ATTLIST image alt (#PCDATA)+>

<!ELEMENT verbinput EMPTY>
<!ATTLIST image src (%basic.content;)+>

<!ELEMENT verbtabinput EMPTY>

<!ELEMENT cs EMPTY>
<!ATTLIST cs tag (%basic.content;)+>

<!ELEMENT env EMPTY>
<!ATTLIST env name (%basic.content;)+>

<!ELEMENT envvar EMPTY>
<!ATTLIST envvar name (%basic.content;)+>

<!ELEMENT tabular (tr)+>
<!ATTLIST tabular spec (#PCDATA)+ #REQUIRED>

<!ELEMENT tr (td)+>

<!ELEMENT td (%basic.content;)+>
<!ATTLIST td span (#PCDATA)+>
<!ATTLIST td spec (#PCDATA)+>

<!ELEMENT br EMPTY>
<!ELEMENT hr EMPTY>
<!ELEMENT LaTeX EMPTY>
<!ELEMENT TeX EMPTY>
<!ELEMENT app EMPTY>
<!ELEMENT appversion EMPTY>
<!ELEMENT nbsp EMPTY>
<!ELEMENT qquad EMPTY>
<!ELEMENT fndagmark EMPTY>
<!ELEMENT hash EMPTY>
<!ELEMENT emdash EMPTY>
<!ELEMENT ldots EMPTY>
<!ELEMENT cont EMPTY>

=== nlct/flowframtk/src/doc/flowframtk-en.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE manual SYSTEM "flowframtk.dtd">
<manual fontenc="T1">
  <preamble>
    <!-- Document Info -->
    <title>User Manual for <dict tag="appname"/> version
      <dict tag="appversion" /></title>
    <author>Nicola L. C. Talbot<br/><url www="www.dickimaw-books.com" /></author>
<!--
    <author>Another Author<br />Affliation or URL</author>
    <author>Translated by Some One<br />Affliation or URL</author>
-->
    <date><dict tag="appdate" /></date>

    <!-- Define Abbreviations -->

    <newacro short="GUI" long="graphical user interface" tag="gui">
      An application with windows and buttons in which the user
      can point and click with the mouse.
    </newacro>

    <newacro short="JDK" long="Java Standard Edition SDK" tag="jdk">
      A development environment for building
       applications, applets and components using the Java
       programming language.
    </newacro>

    <newacro short="JRE" long="Java Runtime Environment" tag="jre"> 
      Allows end-users to run Java applications.
    </newacro>

    <newacro short="JVM" long="Java Virtual Machine" tag="jvm">
      Also known as the Java Runtime Environment.
    </newacro>

    <newacro short="MDI" long="multiple-Document interface" tag="mdi" >
      A main (parent) window containing child
       windows allowing you to process several documents in
       parallel.
    </newacro>

    <newacro prefix="an " prefixfirst="a~"
      short="SVG" long="scalable vector graphics" tag="svg" >
      A Modularized language for describing
      two-dimensional vector and mixed vector/raster graphics in XML.
    </newacro>


    <!-- Define Terms. If a description is
         included it's a glossary term otherwise it goes in the index. -->

    <newterm tag="ajr" text="AJR">
      <app/>'s native ASCII format. Files in this format 
      should have the extension <ext name="ajr"/>. This format is 
      primarily provided to assist conversion to and from JDR files 
      or for version control.
    </newterm>

    <newterm tag="jdr" text="JDR">
      <app/>'s native binary format. Files in this format 
      should have the extension <ext name="jdr"/>.
    </newterm>

    <newterm tag="Java" text="Java">
     A platform-independent object-orientated language.
    </newterm>

    <newterm tag="JavaHelp" text="JavaHelp">
     An optional package of the JRE enabling applications to use a native browser
     to display help topics.
    </newterm>

    <newterm tag="grid" text="grid" >
     Tick marks located at regular intervals on the canvas. The grid can be locked so
     that new points will be placed at the tick nearest the specified
     position.
    </newterm>

    <newterm indexplural="true" tag="toolbar" text="toolbar">
    The two panels containing buttons, the horizontal toolbar is positioned at
    the top of <app/>'s main window, the vertical toolbar is
    positioned along the left edge of the main window.
    </newterm>

    <newterm tag="statusbar" text="status bar">
    The status bar is the horizontal panel positioned along the bottom of
    <app/>'s main window.
    </newterm>

    <newterm indexplural="true" tag="ruler" text="ruler">
    The two panels containing the horizontal and vertical rulers.
    </newterm>

    <newterm tag="canvas" text="canvas" plural="canvases">
    The white area on which you construct your picture.
    </newterm>

    <newterm tag="shape" text="shape">
    Either a path, text-path or a composite shape.
    </newterm>

    <newterm tag="path" text="path">
    A shape made up of line segments, moves and cubic Bézier segments
    </newterm>

    <newterm tag="textarea" text="text area">
    An object consisting of a single line of text. The text may be moved,
    scaled, rotated, sheared or converted to a path.
    </newterm>

    <newterm tag="textpath" text="text-path">
    A composite object formed by combining a path and a text area
    to create a text along a path effect. The underlying path is
    only visible when editing the text-path object using the edit path
    function. Transformations (rotating, scaling and shearing) are
    applied to the path not to the text.
    </newterm>

    <newterm tag="compositeshape" text="composite shape">
    A shape that is described by an underlying shape
    and a means of transforming it, such as apply symmetry or replicas.
    </newterm>

    <newterm tag="symmetricshape" text="symmetric shape">
    A composite shape that is formed by the underlying shape
    added to its reflection in a line a symmetry. Depending on how it's
    created, the symmetric shape may be drawn as a single shape, or the
    underlying shape and its reflection may be drawn independently of
    each other. The line of symmetry has two control points that can be
    adjusted to change the overall shape.
    </newterm>

    <newterm tag="pattern" text="pattern">
    A composite shape formed by repeatedly applying a given
    transformation on a shape. Each pattern has a specified number of
    replicas. The underlying shape may or may not be visible. The
    pattern mode determines whether the underlying path and replicas are
    drawn in one go (single mode) or whether they are drawn
    independently of each other (multi-mode). Transformations (rotating,
    scaling and shearing) are applied to the path not to the text.
    </newterm>

    <newterm tag="rotationalpattern" text="rotational pattern">
    A pattern where the replicas are created
    by rotating the underlying path. In addition to the control points
    defining the underlying shape, rotational patterns also have a control
    point that governs the point of rotation.
    </newterm>

    <newterm tag="scaledpattern" text="scaled pattern">
    A pattern where the replicas are created
    by scaling the underlying path. In addition to the control points
    defining the underlying shape, scaled patterns also have two control
    points governing the scale anchor and the scale direction.
    </newterm>

    <newterm tag="spiralpattern" text="spiral pattern">
    A pattern where the replicas are created
    by rotating and translating the underlying path so that the replicas
    are aligned along a spiral. In addition to the control points
    defining the underlying shape, spiral patterns also have two control points
    that govern the anchor and offset.
    </newterm>

    <newterm tag="pathattributes" text="path attributes">
    The line <dict tag="colour"/>, fill <dict tag="colour"/> and line styles for the path.
    </newterm>

    <newterm tag="textattributes" text="text attributes">
    The text <dict tag="colour"/> and font.
    </newterm>

    <newterm tag="storageunit" text="storage unit">
    The length unit used when storing co-ordinates. The default unit
    is bp (PostScript point) but may be changed in the configuration
    dialog.
    </newterm>

    <newterm tag="controlpt" text="control point">
    The points that define a path. Line segments and gaps have two control
    points, at the start and end, cubic Bézier segments have four
    control points: one at the start of the segment, one at the end of
    the segment, and two others that define the curvature of the segment.
    Adjacent segments share a common control point. When a path is under
    construction, or is being edited, the control points are shown as
    orange or red squares. Composite paths also have control points that
    govern how the full path is created from the underlying shape. The
    composite control points are <dict tag="colour" />ed differently to the standard
    path controls.
    </newterm>

    <newterm tag="ptindex" text="control point index" plural="control point indexes">
    Each control point defining a given path or composite
    shape has an index relative to the initial control point (at the
    start of the path). Use <kbd key="F6"/> (in edit path mode) to cycle
    through the points in increasing order of index.
    </newterm>

    <newterm tag="object" text="object">
    A path, text area, text-path, bitmap or group.
    </newterm>

    <newterm tag="group" text="group">
    A collection of <plural tag="object"/> treated as a single entity.
    </newterm>

    <newterm tag="bbox" text="bounding box" plural="bounding boxes">
    The smallest rectangle that encompasses the <term tag="object"/>.
    </newterm>

    <newterm tag="stack" text="stack" >
    List of <plural tag="object"/> that make up the image, 
    in the order in which they should be painted on the canvas.
    A <term tag="group"/> is essentially a sub-stack.
    </newterm>

    <newterm tag="stackingorder" text="stacking order">
    The order in which <plural tag="object"/> are painted on the canvas.
    To determine the reverse stacking order, deselect all objects, then
    use <kbd key="F6"/> to cycle through the stack starting from the
    frontmost object. Reverse this list to obtain the stacking order.
    Note that the frontmost object is the last object in the <term tag="stack"/>, not
    the first.
    </newterm>

    <newterm tag="frontobject" text="frontmost object">
    The last object to be painted on the canvas.
    </newterm>

    <newterm tag="front" alias="frontobject" />

    <newterm tag="backobject" text="backmost object">
    The first object to be painted on the canvas.
    </newterm>

    <newterm tag="back" alias="backobject" />

    <newterm tag="vectorgraphics" text="vector graphics">
    A means of describing images through the use of points, lines and curves.
    </newterm>

    <newterm tag="raster" text="raster graphics">
    Representing images as a collection of pixels. Also called a bitmap.
    </newterm>

    <newterm tag="bitmap" alias="raster" />

    <newterm tag="construction" text="construction mode">
    Any of the tools except the select tool.
    </newterm>

    <newterm tag="pt" >
    <TeX/>'s point. Not to be confused with bp (a PostScript point).
    72.27pt=1in.
